#!/usr/bin/python
###############################################################################
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.    #
#                                                                             #
#  Licensed under the Apache License Version 2.0 (the "License"). You may not #
#  use this file except in compliance with the License. A copy of the License #
#  is located at                                                              #
#                                                                             #
#      http://www.apache.org/licenses/LICENSE-2.0/                                        #
#                                                                             #
#  or in the "license" file accompanying this file. This file is distributed  #
#  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, express #
#  or implied. See the License for the specific language governing permis-    #
#  sions and limitations under the License.                                   #
###############################################################################


from aws_xray_sdk.core import xray_recorder

from ..common.log import get_logger

logger = get_logger(__name__)


@xray_recorder.capture("resolve_artifact_metadata")
def resolve_artifact_metadata(s3_client, s3_bucket_name, prefix):
    # artifact_locaton, artifact_size, sha256
    # Paginated. list_objects_v2 returns at most 1000 keys per call, so a case
    # prefix holding more artifacts than that silently reported metadata for the
    # first page only - the same shape of bug as the unpaginated
    # DescribeInstanceInformation calls elsewhere in this solution.
    contents = []
    paginator = s3_client.get_paginator("list_objects_v2")
    for page in paginator.paginate(Bucket=s3_bucket_name, Prefix=prefix):
        contents.extend(page.get("Contents", []))

    artifact_metadata = []

    for obj in contents:
        object_key = obj["Key"]
        object_size = obj["Size"]
        file_name_with_extension = object_key.split("/")[-1]

        # any(), not a loop that reassigns. The loop this replaces had no break
        # and no accumulation, so only the *last* underscore-separated part
        # decided: "vol_sha256_part1.txt" was classified as not being a digest
        # file, and the code then went looking for a digest of the digest.
        is_sha_256 = any(
            "sha256" in part for part in object_key.split("_")
        )

        if not is_sha_256:
            # get filename without extension and add _sha256.txt
            filename_parts = file_name_with_extension.split(".")
            filename = (
                ".".join(filename_parts[0:-1])
                if len(filename_parts) > 1
                else ".".join(filename_parts)
            )
            sha_value = None

            # Against every page, not just the first: the digest sidecar can
            # easily be on a later page than the artifact it belongs to.
            if any(
                candidate["Key"] == f"{prefix}/{filename}_sha256.txt"
                for candidate in contents
            ):
                sha_response = s3_client.get_object(
                    Bucket=s3_bucket_name,
                    Key=f"{prefix}/{filename}_sha256.txt",
                )
                sha_value = (
                    sha_response["Body"].read().decode("utf-8")
                    if sha_response
                    else "SHA value was not generated by SSM investigation document"
                )

            artifact_metadata.append(
                {
                    "artifact_location": object_key,
                    "artifact_size": object_size,
                    "sha256": sha_value,
                }
            )

    return artifact_metadata
